name: Format Code

on:
  push:
    branches: [main]

  pull_request:
    branches-ignore: [main]

jobs:

  format:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3



    - uses: DavidAnson/markdownlint-cli2-action@v10
      with:
        command: config
        globs: |
          .markdownlint-cli2.jsonc
          **/*.md


    - uses: EndBug/add-and-commit@v9
      with:
        # author_email: ${{ vars.ENV_FORMATTER_AUTHOR_EMAIL }}
        # author_name: ${{ vars.ENV_FORMATTER_AUTHOR_NAME }}
        fetch: true
        # message: ${{ vars.ENV_FORMATTER_COMMIT_MESSAGE }}
        pull: '--rebase'
        push: true
